fragment WorkParts on Work {
  __typename
  title
  category
  image
  link
  description
  gallery
  meta_description
  body
}

fragment PagesParts on Pages {
  __typename
  title
  meta_description
  heroTitle
  backgroundVideo
  buttons {
    __typename
    text
    link
    isExternal
  }
}

fragment AboutParts on About {
  __typename
  title
  meta_description
  body
  contactLinks {
    __typename
    text
    link
    isExternal
  }
}

fragment Work_pageParts on Work_page {
  __typename
  title
  meta_description
  subtitle
}

fragment ContactParts on Contact {
  __typename
  title
  meta_description
  body
  actionButton {
    __typename
    text
    link
  }
}
