backend:
  name: github
  repo: cozunap/ozuna.ca
  base_url: https://ozuna.pages.dev
  auth_endpoint: auth
  branch: main

publish_mode: editorial_workflow

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "work"
    label: "Work"
    folder: "src/content/work"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["web", "graphic"]}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        types:
          - label: "Text Block"
            name: "text"
            widget: "object"
            fields:
              - {label: "Content", name: "content", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            types:
              - label: "Text Block"
                name: "text"
                widget: "object"
                fields:
                  - {label: "Content", name: "content", widget: "markdown"}
